# Generated by Django 3.2.5 on 2021-07-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kospi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10, unique=True, verbose_name='날짜')),
                ('close', models.FloatField(null=True, verbose_name='종가')),
                ('open', models.FloatField(null=True, verbose_name='시가')),
            ],
        ),
    ]
