# Generated by Django 3.2.5 on 2021-08-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kospi',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='kospi',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='kospi',
            name='open',
            field=models.FloatField(null=True),
        ),
    ]
